function Hd = drop20
%DROP20 Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.10 and the Signal Processing Toolbox 6.13.
%
% Generated on: 26-Nov-2013 02:41:45
%

% IIR maximally flat Lowpass filter designed using the MAXFLAT function.

% All frequency values are in Hz.
Fs = 1000;  % Sampling Frequency

Nb = 8;   % Numerator Order
Na = 8;   % Denominator Order
Fc = 20;  % Cutoff Frequency

% Calculate the second-order sections coefficients to avoid round-off
% errors.
[b,a,b1,b2,sos_var,g] = maxflat(Nb, Na, Fc/(Fs/2));
Hd                    = dfilt.df2sos(sos_var, g);

% [EOF]
