function Hd = filter1
%FILTER1 Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.10 and the Signal Processing Toolbox 6.13.
%
% Generated on: 14-Nov-2013 14:03:53
%

Fstop1 = 0.001;  % First Stopband Frequency
Fpass1 = 0.1;    % First Passband Frequency
Fpass2 = 0.2;    % Second Passband Frequency
Fstop2 = 0.21;   % Second Stopband Frequency
Astop1 = 60;     % First Stopband Attenuation (dB)
Apass  = 1;      % Passband Ripple (dB)
Astop2 = 60;     % Second Stopband Attenuation (dB)

h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
                     Fpass2, Fstop2, Astop1, Apass, Astop2);

Hd = design(h, 'equiripple');



% [EOF]
